{
    'name': "Advanced Jobs",
    'version': '14.0.0.0.0',
    'sequence': '4',
    'summary': """ """,
    'description': """""",
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'website': "https://www.cybrosys.com",
    'category': 'Accounting/Accounting',
    'depends': ['base', 'website_hr_recruitment', 'website'],
    'data': ['views/website_jobs.xml',
             'views/job_form.xml'],
    'demo': [],
    'qweb': [],
    'images': [],
    'license': 'LGPL-3',
    'post_init_hook': '_fields_whitelist',
    'installable': True,
    'auto_install': False,
}
