{
    'name': "Document Additional",
    'version': '13.0.0.0.0',
    'sequence': '4',
    'summary': """ """,
    'description': """""",
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'website': "https://www.cybrosys.com",
    'category': '',
    'depends': ['document_management', 'ks_binary_file_preview', 'portal'],
    'data': ['views/document_directory_kanban.xml',
             'views/document_view.xml',
             'views/document_kanban.xml',
             'views/document_portal.xml'],
    'demo': [],
    'qweb': [],
    'images': [],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
}
